[[redirects]]
  from = "https://selba.mn/api/*"
  to = "https://api.selba.mn/:splat"
  status = 200
  force = true

[context.production.environment]
REACT_APP_SERVICE_URL = "https://api.selba.mn"

[context.development.environment]
REACT_APP_SERVICE_URL = "localhost:8080"