[[redirects]]
  from = "https://selba.mn/login"
  to = "https://selba.mn/"
  status = 200
  force = true

[[redirects]]
  from = "https://selba.mn/api/*"
  to = "https://api.selba.mn/api/:splat"
  status = 200
  force = true