[[redirects]]
  from = "/api"
  to = "https://api.selba.mn"
  status = 200
  force = true
  query = {path = ":path"}

[context.production.environment]
REACT_APP_SERVICE_URL = "https://api.selba.mn"

[context.development.environment]
REACT_APP_SERVICE_URL = "localhost:8080"